// Resúmenes de las fichas técnicas en assets/documents; RELEASE espera su ficha.
export const additiveProducts = {
  flow: {
    name: "FORTICEM FLOW",
    descriptor: "Plastificante · reductor de agua",
    problem: "Más trabajabilidad para concreto y mortero",
    description: "Aditivo líquido plastificante que mejora la trabajabilidad de mezclas de concreto y mortero y ayuda a optimizar la relación agua/cemento.",
    applications: ["Concreto y mortero preparados en obra", "Mezclas que requieren mayor fluidez y compactación"],
    benefits: ["Mejora la fluidez y la cohesión de la mezcla", "Facilita la compactación y ayuda a reducir la segregación"],
    dosage: "0,72 % a 1,0 % del peso del cemento; aproximadamente 250 a 348 ml por bolsa de 42,5 kg.",
    use: ["Añadir a la mezcla o al agua de amasado.", "Ajustar la dosis mediante pruebas de laboratorio según cemento, agregados y agua."],
    properties: [["Apariencia", "Líquido marrón"], ["Densidad a 20 °C", "1,18 a 1,22 g/cm³"], ["pH", "6,0 a 7,5"]],
    storage: "Evitar temperaturas inferiores a 5 °C o superiores a 35 °C. Vida útil indicada: 12 meses desde la fabricación, con almacenamiento adecuado.",
    presentations: "4 L · 20 L · 200 L · 1000 L",
    sheet: "forticem-flow.pdf",
  },
  "flow-plus": {
    name: "FORTICEM FLOW+",
    descriptor: "Superplastificante · alta reducción de agua",
    problem: "Mayor fluidez sin aumentar la relación agua/cemento",
    description: "Aditivo líquido de alto desempeño para mejorar la fluidez del concreto y mortero y reducir el agua requerida en la mezcla.",
    applications: ["Concretos de alta resistencia y bombeables", "Prefabricados y pretensados", "Concretos autocompactantes", "Morteros de alto desempeño"],
    benefits: ["Permite reducir el contenido de agua según el diseño de mezcla", "Favorece la compacidad y el acabado superficial"],
    dosage: "0,3 % a 0,7 % del peso del cemento.",
    use: ["Agregar directamente a la mezcla o al agua de amasado.", "Verificar la dosis y el desempeño con ensayos para la mezcla específica."],
    properties: [["Apariencia", "Líquido marrón"], ["Densidad a 20 °C", "1,15 a 1,25 g/cm³"], ["pH", "6,5 a 7,5"]],
    storage: "Conservar cerrado en un lugar fresco y ventilado; evitar temperaturas inferiores a 5 °C o superiores a 35 °C. Vida útil indicada: 12 meses desde la fabricación.",
    presentations: "4 L · 20 L · 200 L · 1000 L",
    sheet: "forticem-flow-plus.pdf",
  },
  cure: {
    name: "FORTICEM CURE",
    descriptor: "Curador formador de película",
    problem: "Ayuda a conservar la humedad durante el curado",
    description: "Compuesto líquido en dispersión acuosa que forma una membrana sobre el concreto fresco y reduce la evaporación del agua de amasado.",
    applications: ["Losas, pavimentos y pisos industriales", "Muros, columnas y elementos estructurales", "Prefabricados y superficies expuestas al sol o al viento"],
    benefits: ["Reduce la pérdida de humedad", "Favorece el curado y ayuda a disminuir la fisuración superficial"],
    dosage: "Rendimiento aproximado de 1 L por 5 m² con tres pasadas; puede variar según textura y absorción de la superficie.",
    use: ["Aplicar cuando haya desaparecido el agua de exudación.", "Distribuir una capa uniforme con brocha, rodillo o pulverizador de baja presión."],
    properties: [["Apariencia", "Líquido traslúcido"], ["Densidad a 20 °C", "1,05 a 1,11 g/cm³"], ["pH", "4,5 a 6,0"]],
    presentations: "4 L · 20 L · 200 L · 1000 L",
    sheet: "forticem-cure.pdf",
  },
  fast: {
    name: "FORTICEM FAST",
    descriptor: "Acelerante para concreto y mortero",
    problem: "Reduce el tiempo de fraguado y favorece la resistencia temprana",
    description: "Acelerante líquido libre de cloruros para concreto y mortero, pensado para condiciones normales o frías y procesos que requieren desmolde rápido.",
    applications: ["Prefabricados y elementos estructurales", "Concreto proyectado", "Pisos industriales y capas de rodadura", "Obras en clima frío"],
    benefits: ["Acelera el fraguado inicial", "Favorece el desarrollo de resistencia a edades tempranas"],
    dosage: "0,5 % a 0,9 % del peso del cemento; aproximadamente 158,6 a 285,45 ml por bolsa de 42,5 kg.",
    use: ["Realizar ensayos previos para establecer la dosis óptima según mezcla, clima y resistencia requerida."],
    properties: [["Apariencia", "Líquido amarillento"], ["Densidad a 20 °C", "1,34 a 1,37 g/cm³"], ["pH", "7,0 a 9,5"], ["Cloruros", "Libre de cloruros"]],
    storage: "Almacenar cerrado en un lugar fresco, protegido del sol y de temperaturas inferiores a 5 °C. Vida útil indicada: 12 meses en envase original cerrado.",
    presentations: "4 L · 20 L · 200 L · 1000 L",
    sheet: "forticem-fast.pdf",
  },
  release: {
    name: "FORTICEM RELEASE",
    descriptor: "Desmoldante para concreto",
    problem: "Facilitar un desmolde limpio y controlado",
    description: "Producto formulado para apoyar la separación entre el concreto y el molde durante procesos de fabricación y obra.",
    applications: ["Prefabricados de concreto", "Encofrados", "Procesos repetitivos de moldeo"],
  },
  seal: {
    name: "FORTICEM SEAL",
    descriptor: "Impermeabilizante integral",
    problem: "Reduce la absorción capilar del concreto",
    description: "Aditivo impermeabilizante líquido que se incorpora a la mezcla para mejorar su resistencia frente a la penetración de agua.",
    applications: ["Cimentaciones, muros de contención, tanques y canales", "Obras costeras o expuestas a humedad", "Morteros de revoque y elementos exteriores", "Prefabricados expuestos a humedad permanente"],
    benefits: ["Mejora la impermeabilidad desde la mezcla", "Ayuda a aumentar la durabilidad en ambientes húmedos"],
    dosage: "1,0 % a 2,0 % del peso del cemento, según las condiciones del proyecto.",
    use: ["Incorporar al agua de mezclado o durante el amasado.", "Mezclar hasta lograr una distribución homogénea."],
    properties: [["Apariencia", "Líquido lechoso, blanco a ligeramente opalescente"], ["Densidad a 20 °C", "1,01 a 1,05 g/cm³"], ["pH", "10,0 a 12,0"]],
    storage: "Evitar temperaturas inferiores a 5 °C o superiores a 35 °C. Vida útil indicada: 12 meses desde la fabricación, con almacenamiento adecuado.",
    presentations: "4 L · 20 L · 200 L · 1000 L",
    sheet: "forticem-seal.pdf",
  },
};
